# Generated by Django 3.0.5 on 2024-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity given for free'),
        ),
        migrations.AddField(
            model_name='product',
            name='required_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Set to 0 to disable promotion'),
        ),
    ]
