# Generated by Django 3.0.5 on 2024-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20240602_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
