# Generated by Django 5.1.1 on 2024-09-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0010_returnrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
